const data = {
  products: [
    {
      name: 'Chocolate Chip Cookies',
      slug: 'chocolate-chip-cookies',
      category: 'cookies',
      image: '/images/chocolate-chip-cookies.jpg',
      price: '1.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Chocolate Chip Cookies',
    },
    {
      name: 'Oatmeal Chocolate Chip Cookies',
      slug: 'oatmeal-chocolate-chip-cookies',
      category: 'cookies',
      image: '/images/oatmeal-chocolate-chip-cookies.jpg',
      price: '1.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Oatmeal Chocolate Chip Cookies',
    },
    {
      name: 'White Chocolate Macadamia Nut Cookies',
      slug: 'white-chocolate-Macadameia-nut-cookies',
      category: 'cookies',
      image: '/images/white-chocolate-macadamia-nut-cookies.jpg',
      price: '1.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju White Chocolate Macadamia Nut Cookies',
    },
    {
      name: 'Peanut Butter Chip Cookies',
      slug: 'peanut-butter-chip-cookies',
      category: 'cookies',
      image: '/images/peanut-butter-chip-cookies.jpg',
      price: '1.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Peanut Butter Chip Cookies',
    },
    {
      name: 'Butterscotch Pecan Cookies',
      slug: 'Butterscotch-pecan-cookies',
      category: 'cookies',
      image: '/images/butterscotch-pecan-cookies.jpg',
      price: '1.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Butterscotch Pecan Cookies',
    },
    {
      name: 'Keto Chocolate Chip Cookies',
      slug: 'keto-chocolate-chip-cookies',
      category: 'keto-cookies',
      image: '/images/chocolate-chip-cookies.jpg',
      price: '3.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Keto Chocolate Chip Cookies',
    },
    {
      name: 'Keto Oatmeal Chocolate Chip Cookies',
      slug: 'keto-oatmeal-chocolate-chip-cookies',
      category: 'keto-cookies',
      image: '/images/oatmeal-chocolate-chip-cookies.jpg',
      price: '3.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Oatmeal Chocolate Chip Cookies',
    },
    {
      name: 'Keto White Chocolate Macadamia Nut Cookies',
      slug: 'keto-white-chocolate-Macadameia-nut-cookies',
      category: 'keto-cookies',
      image: '/images/white-chocolate-macadamia-nut-cookies.jpg',
      price: '3.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Keto White Chocolate Macadamia Nut Cookies',
    },
    {
      name: 'Keto Peanut Butter Chip Cookies',
      slug: 'keto-peanut-butter-chip-cookies',
      category: 'keto-cookies',
      image: '/images/peanut-butter-chip-cookies.jpg',
      price: '3.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Keto Peanut Butter Chip Cookies',
    },
    {
      name: 'Keto Butterscotch Pecan Cookies',
      slug: 'keto-butterscotch-pecan-cookies',
      category: 'keto-cookies',
      image: '/images/butterscotch-pecan-cookies.jpg',
      price: '3.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Keto Butterscotch Pecan Cookies',
    },
    {
      name: 'Chocolate Chip Brownies',
      slug: 'chocolate-chip-brownies',
      category: 'cookies',
      image: '/images/chocolate-chip-brownies.jpg',
      price: '2.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Chocolate Chip Brownies',
    },
    {
      name: 'Oatmeal Chocolate Chip Brownies',
      slug: 'oatmeal-chocolate-chip-brownies',
      category: 'cookies',
      image: '/images/oatmeal-chocolate-chip-brownies.jpg',
      price: '2.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Oatmeal Chocolate Chip Brownies',
    },
    {
      name: 'White Chocolate Macadamia Nut Brownies',
      slug: 'white-chocolate-Macadameia-nut-brownies',
      category: 'cookies',
      image: '/images/white-chocolate-macadamia-nut-brownies.jpg',
      price: '2.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju White Chocolate Macadamia Nut Brownies',
    },
    {
      name: 'Peanut Butter Chip Brownies',
      slug: 'peanut-butter-chip-brownies',
      category: 'cookies',
      image: '/images/peanut-butter-chip-brownies.jpg',
      price: '2.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Peanut Butter Chip Brownies',
    },
    {
      name: 'Butterscotch Pecan Brownies',
      slug: 'Butterscotch-pecan-brownies',
      category: 'cookies',
      image: '/images/butterscotch-pecan-brownies.jpg',
      price: '2.99',
      brand: 'Juju',
      rating: '4.5',
      numReviews: '10',
      counInStock: '10',
      description: 'Juju Butterscotch Pecan Brownies',
    },
  ],
};

export default data;
